version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/node:18.12.1
    steps:
      - checkout
      - restore_cache:
          key: lock-v1-{{ checksum "package-lock.json" }}--{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}--{{ arch }}

      - run: npm ci

      - save_cache:
          key: lock-v1-{{ checksum "package-lock.json" }}--{{ arch }}
          paths:
            - .cache/package-lock

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}--{{ arch }}
          paths:
            - node_modules

      - run: npm run lint

  test:
    docker:
      - image: cimg/node:18.12.1
      - image: cimg/postgres:14.5
        environment:
          POSTGRES_USER: unumid
    steps:
      - checkout
      - restore_cache:
          key: lock-v1-{{ checksum "package-lock.json" }}--{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}--{{ arch }}

      - run: npm ci

      - save_cache:
          key: lock-v1-{{ checksum "package-lock.json" }}--{{ arch }}
          paths:
            - .cache/package-lock

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}--{{ arch }}
          paths:
            - node_modules

      - run:
          name: Jest Tests
          command: npm run test

workflows:
  lint-and-test:
    jobs:
        - lint
        - test:
            requires:
                - lint
